# Generated by Django 2.1.3 on 2018-11-10 03:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subcategories_file',
            field=models.CharField(default=uuid.uuid4(), max_length=1024),
            preserve_default=False,
        ),
    ]
