# Generated by Django 2.1.3 on 2018-11-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20181110_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='week_day',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
