# Generated by Django 2.1.3 on 2018-11-10 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20181110_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsubcategories',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Subcategory'),
        ),
    ]
